###  Why do you need the OPEN APIs?
* Maximize the value of your **technology investment**
* Collaborate Easily, Centralize Assets, Support Organization Agility!
* Quickly access an **<font color=green>Massively Parallel Distributed, Fault Tolerant High Performance In-Memory Environment </font>** in your **own *"favorite"* language from your <u>own preferred interface</u>**
* Build custom high quality user experiences that embedding analytics or perform quick adhoc analysis

Learn more about how it helps [here](https://www.sas.com/en_us/software/platform/open.html)

Ok, there is a lot of **value** -- but how do you get started?

The rest of this demonstration is centered around this topic of **"Getting started with basic analysis"** using Python SWAT for Viya (CAS). The same concepts apply for other languages as well.

* User Personas :- Data Scientists, Data Engineers & Application Developers

Before we get started, here's a quick recap of **how CAS works with any SWAT package**
 ><font color=orange>Notice how SWAT Methods are converted into SWAT actions under the hood.</font>

![alt text](CAS_Access_BasicArchitecture.png "SWAT-->CAS Actions --> Getting things done")
<font size=2px>Smith, Kevin D.; Meng, Xiangxiang. SAS Viya: The Python Perspective (p. 51). SAS Institute. Kindle Edition.</font>

Ok, with that out of the way - let's do some simple stuff with SWAT

Import the SWAT package and do some house keeping stuff

In [1]:
import _config,swat
from swat.render import render_html
import pandas as pd
pd.set_option('display.float_format', lambda x: '%.2f' % x)
from IPython.display import Image

Now, we can login to our CAS server and **<font color=green>connect using REST over http</font>**

In [2]:
user,pswd = _config.login()
host='racesx12070.demo.sas.com'
portnum=8777 #REST port
conn = swat.CAS(host,portnum,user,pswd,protocol='http')

Next we can quickly check what libraries are available to us on this connection string

In [3]:
conn.caslibinfo()

,Name,Type,Description,Path,Definition,Subdirs,Local,Active,Personal,Hidden
0,CASUSER(sasdemo),PATH,Personal File System Caslib,/home/sasdemo/casuser/,,1.00,0.00,1.00,1.00,0.00
1,DemoData,PATH,"DemoCenter Shared and writeable caslib, access...",/opt/sasinside/DemoData/,,0.00,0.00,0.00,0.00,0.00
2,Formats,PATH,Stores user defined formats.,/opt/sas/viya/config/data/cas/default/formats/,,1.00,0.00,0.00,0.00,0.00
3,Models,PATH,Stores models created by Visual Analytics for ...,/opt/sas/viya/config/data/cas/default/models/,,0.00,0.00,0.00,0.00,0.00
4,Public,PATH,"Shared and writeable caslib, accessible to all...",/opt/sas/viya/config/data/cas/default/public/,,1.00,0.00,0.00,0.00,0.00
5,SystemData,PATH,"Stores application generated data, used for ge...",/opt/sas/viya/config/data/cas/default/sysData/,,0.00,0.00,0.00,0.00,0.00

In [28]:
conn.fileinfo(caslib='casuser') #list everything in the path

,Permission,Owner,Group,Name,Size,Encryption,Time
0,-rwxr-xr-x,sasdemo,sas,cardata.sas7bdat,204603392,,19May2017:05:25:23

Load the file in the path into the CAS library using the load table action

In [29]:

out = conn.loadtable('cardata.sas7bdat', casout = dict(name='CARDATA',caslib='casuser'))

NOTE: Cloud Analytic Services made the file cardata.sas7bdat available as table CARDATA in caslib CASUSER(sasdemo).

Investigate the `out` variable - what you'll see is that it returns a CASResults Object

In [30]:
out

[tableName]

 'CARDATA'

[caslib]

 'CASUSER(sasdemo)'

[casTable]

 CASTable('CARDATA', caslib='CASUSER(sasdemo)')

+ Elapsed: 1.66s, user: 0.952s, sys: 0.703s, mem: 17.7mb

You can subset the CASResults Object just like a regular python ordered dict

In [31]:
out = out.casTable

*To get a quick sneak peek at the data set*
    * Use the SWAT approach with the fetch action
    OR
    * Use the pandas .head() method

In [32]:
out.fetch(to=5)

,ID,isbadbuy,purchase_date,cost,provider,buyer,modelID,year,odometer,color,...,zipcode,state,refprice1,refprice2,refprice3,refprice4,refprice5,refprice6,refprice7,refprice8
0,1.00,good,18429.00,6150.00,MANHEIM,21973.00,2691.00,2007.00,79517.00,GREY,...,32824.00,FL,8363.00,9890.00,12596.00,14608.00,8295.00,9856.00,12099.00,13909.00
1,2.00,good,18123.00,7800.00,OTHER,99761.00,305.00,2008.00,47747.00,BLACK,...,74135.00,OK,8435.00,9341.00,9610.00,10588.00,8802.00,9497.00,10006.00,10757.00
2,3.00,good,18023.00,5900.00,MANHEIM,19619.00,446.00,2006.00,59231.00,BLUE,...,32824.00,FL,6544.00,8170.00,7568.00,9324.00,6544.00,8170.00,7568.00,9324.00
3,4.00,good,18149.00,5500.00,MANHEIM,20928.00,790.00,2006.00,75168.00,RED,...,32824.00,FL,5149.00,6514.00,6061.00,7535.00,4931.00,5967.00,8408.00,9831.00
4,5.00,good,18304.00,4415.00,MANHEIM,21973.00,1066.00,2001.00,79655.00,RED,...,33411.00,FL,2392.00,3163.00,4984.00,5980.00,2733.00,3575.00,4907.00,5712.00

In [33]:
out.head()

,ID,isbadbuy,purchase_date,cost,provider,buyer,modelID,year,odometer,color,...,zipcode,state,refprice1,refprice2,refprice3,refprice4,refprice5,refprice6,refprice7,refprice8
0,1.00,good,18429.00,6150.00,MANHEIM,21973.00,2691.00,2007.00,79517.00,GREY,...,32824.00,FL,8363.00,9890.00,12596.00,14608.00,8295.00,9856.00,12099.00,13909.00
1,2.00,good,18123.00,7800.00,OTHER,99761.00,305.00,2008.00,47747.00,BLACK,...,74135.00,OK,8435.00,9341.00,9610.00,10588.00,8802.00,9497.00,10006.00,10757.00
2,3.00,good,18023.00,5900.00,MANHEIM,19619.00,446.00,2006.00,59231.00,BLUE,...,32824.00,FL,6544.00,8170.00,7568.00,9324.00,6544.00,8170.00,7568.00,9324.00
3,4.00,good,18149.00,5500.00,MANHEIM,20928.00,790.00,2006.00,75168.00,RED,...,32824.00,FL,5149.00,6514.00,6061.00,7535.00,4931.00,5967.00,8408.00,9831.00
4,5.00,good,18304.00,4415.00,MANHEIM,21973.00,1066.00,2001.00,79655.00,RED,...,33411.00,FL,2392.00,3163.00,4984.00,5980.00,2733.00,3575.00,4907.00,5712.00

Nice Utility Function to work in the Notebook Environment

In [34]:
#from IPython.display import HTML
#HTML(out.head().to_html())
from swat.render import render_html
render_html(out.head())

We can easily check some table properties

In [35]:
#conn.tableinfo(name='CARDATA')
out.tableinfo()

,Name,Rows,Columns,Encoding,CreateTimeFormatted,ModTimeFormatted,JavaCharSet,CreateTime,ModTime,Global,Repeated,View,SourceName,SourceCaslib,Compressed,Creator,Modifier
0,CARDATA,1020455,27,utf-8,19May2017:05:26:13,19May2017:05:26:13,UTF8,1810790773.64,1810790773.64,0,0,0,cardata.sas7bdat,CASUSER(sasdemo),0,sasdemo,

And the table's column properties

In [36]:
out.columninfo()
#conn.columninfo('CARDATA')

,Column,Label,ID,Type,RawLength,FormattedLength,Format,NFL,NFD
0,ID,RefId,1,double,8,5,BEST,5,0
1,isbadbuy,,2,char,10,10,$,10,0
2,purchase_date,PurchDate,3,double,8,10,MMDDYY,10,0
3,cost,VehBCost,4,double,8,8,BEST,8,0
4,provider,Auction,5,char,7,7,$CHAR,7,0
5,buyer,BYRNO,6,double,8,5,BEST,5,0
6,modelID,,7,double,8,12,,0,0
7,year,VehYear,8,double,8,4,BEST,4,0
8,odometer,VehOdo,9,double,8,6,BEST,6,0
9,color,Color,10,char,9,9,$CHAR,9,0
10,transmission,Transmission,11,char,6,6,$CHAR,6,0
11,wheeltype1,WheelTypeID,12,char,4,4,$CHAR,4,0
12,wheeltype2,WheelType,13,char,7,7,$CHAR,7,0
13,high_demand,PRIMEUNIT,14,char,4,4,$CHAR,4,0
14,guarantee,AUCGUART,15,char,5,5,$CHAR,5,0
15,warranty_price,WarrantyCost,16,double,8,4,BEST,4,0
16,online,IsOnlineSale,17,double,8,1,BEST,1,0
17,zipcode,VNZIP1,18,double,8,5,BEST,5,0
18,state,VNST,19,char,2,2,$CHAR,2,0
19,refprice1,MMRAcquisitionAuctionAveragePrice,20,double,8,5,BEST,5,0
20,refprice2,MMRAcquisitionAuctionCleanPrice,21,double,8,5,BEST,5,0
21,refprice3,MMRAcquisitionRetailAveragePrice,22,double,8,5,BEST,5,0
22,refprice4,MMRAcquisitonRetailCleanPrice,23,double,8,5,BEST,5,0
23,refprice5,MMRCurrentAuctionAveragePrice,24,double,8,5,BEST,5,0
24,refprice6,MMRCurrentAuctionCleanPrice,25,double,8,5,BEST,5,0
25,refprice7,MMRCurrentRetailAveragePrice,26,double,8,5,BEST,5,0
26,refprice8,MMRCurrentRetailCleanPrice,27,double,8,5,BEST,5,0

Let's get some summary statistics!

In [37]:
out.summary()

,Column,Min,Max,N,NMiss,Mean,Sum,Std,StdErr,Var,USS,CSS,CV,TValue,ProbT
0,ID,1.00,1020455.00,1020455.00,0.00,510228.00,520664713740.00,294580.13,291.61,86777452290.00,354210113860915072.00,88552398299139664.00,57.73,1749.68,0.00
1,purchase_date,17902.00,18626.00,1020455.00,0.00,18283.07,18657050741.00,210.47,0.21,44299.39,341153380126851.00,45205486863.30,1.15,87750.02,0.00
2,cost,1.00,45469.00,1020455.00,0.00,6700.33,6837388153.55,1829.67,1.81,3347705.45,49228955833387.40,3416179412765.42,27.31,3699.30,0.00
3,buyer,835.00,99761.00,1020455.00,0.00,27003.21,27555557520.00,26288.14,26.02,691066261.05,1449289751929658.00,705201330354940.00,97.35,1037.65,0.00
4,modelID,1.00,2797.00,1020455.00,0.00,1424.43,1453571350.00,745.51,0.74,555784.49,2637669744874.00,567152505465.28,52.34,1930.13,0.00
5,year,2001.00,2010.00,1020455.00,0.00,2005.20,2046219146.00,2.22,0.00,4.93,4103089233664.00,5027641.23,0.11,912577.57,0.00
6,odometer,4825.00,115717.00,1020455.00,0.00,71699.56,73166172213.00,14979.49,14.83,224385059.70,5474956822307489.00,228974631713711.00,20.89,4835.22,0.00
7,warranty_price,462.00,7498.00,1020455.00,0.00,1242.02,1267421484.00,565.58,0.56,319876.82,1900577400358.00,326419580459.27,45.54,2218.36,0.00
8,online,0.00,1.00,1020455.00,0.00,0.02,15425.00,0.12,0.00,0.01,15425.00,15191.84,807.19,125.15,0.00
9,zipcode,2764.00,99224.00,1020455.00,0.00,56724.18,57884472689.00,25921.43,25.66,671920319.28,3969113002089559.00,685663777495052.00,45.70,2210.58,0.00
10,refprice1,0.00,35722.00,1020235.00,220.00,6151.24,6275707593.00,2823.09,2.79,7969828.17,46734456337545.00,8131089669240.29,45.89,2200.84,0.00
11,refprice2,0.00,36859.00,1020235.00,220.00,7359.17,7508080231.00,3059.01,3.03,9357535.27,64800095491585.00,9546875640145.85,41.57,2429.95,0.00
12,refprice3,0.00,39080.00,1020235.00,220.00,8515.20,8687507186.00,3434.28,3.40,11794300.17,86008825231252.00,12032946039887.60,40.33,2504.43,0.00
13,refprice4,0.00,41482.00,1020235.00,220.00,9844.89,10044096877.00,3661.60,3.63,13407283.96,112561551819353.00,13678566943749.60,37.19,2715.75,0.00
14,refprice5,0.00,35722.00,1015818.00,4637.00,6114.30,6211013966.00,2720.64,2.70,7401894.34,45494960374246.00,7518970102517.16,44.50,2265.08,0.00
15,refprice6,0.00,36859.00,1015818.00,4637.00,7315.79,7431515598.00,2936.53,2.91,8623235.59,63127069222204.00,8759629303520.44,40.14,2510.93,0.00
16,refprice7,0.00,39080.00,1015818.00,4637.00,8729.83,8867914873.00,3306.59,3.28,10933526.67,88521820323557.00,11106462262590.70,37.88,2660.93,0.00
17,refprice8,0.00,41062.00,1015818.00,4637.00,10048.56,10207504985.00,3516.16,3.49,12363356.94,115129602926337.00,12558908157392.30,34.99,2880.34,0.00

And again, the pandas way works too!

In [38]:
#out.describe(percentiles=[i/100 for i in range(0,100,5)]).to_csv('file.csv')
out.describe(percentiles=[i/100 for i in range(0,100,5)])

,ID,purchase_date,cost,buyer,modelID,year,odometer,warranty_price,online,zipcode,refprice1,refprice2,refprice3,refprice4,refprice5,refprice6,refprice7,refprice8
count,1020455.00,1020455.00,1020455.00,1020455.00,1020455.00,1020455.00,1020455.00,1020455.00,1020455.00,1020455.00,1020235.00,1020235.00,1020235.00,1020235.00,1015818.00,1015818.00,1015818.00,1015818.00
mean,510228.00,18283.07,6700.33,27003.21,1424.43,2005.20,71699.56,1242.02,0.02,56724.18,6151.24,7359.17,8515.20,9844.89,6114.30,7315.79,8729.83,10048.56
std,294580.13,210.47,1829.67,26288.14,745.51,2.22,14979.49,565.58,0.12,25921.43,2823.09,3059.01,3434.28,3661.60,2720.64,2936.53,3306.59,3516.16
min,1.00,17902.00,1.00,835.00,1.00,2001.00,4825.00,462.00,0.00,2764.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
0%,1.00,17902.00,1.00,835.00,1.00,2001.00,4825.00,462.00,0.00,2764.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
5%,51023.00,17945.00,3900.00,1235.00,245.00,2001.00,45310.00,533.00,0.00,22801.00,2290.00,3143.00,3422.00,4451.00,2327.00,3200.00,3699.00,4726.00
10%,102046.00,17980.00,4210.00,5546.00,370.00,2002.00,50210.00,671.00,0.00,27542.00,2752.00,3700.00,4295.00,5393.00,2765.00,3728.00,4589.00,5717.00
15%,153069.00,18023.00,4660.00,8655.00,452.00,2003.00,54188.00,754.00,0.00,28625.00,3150.00,4171.00,4937.00,6068.00,3164.00,4182.00,5220.00,6358.00
20%,204091.50,18070.00,5000.00,16926.00,610.00,2003.00,58711.00,834.00,0.00,29697.00,3541.00,4613.00,5467.00,6685.00,3546.00,4626.00,5755.00,6947.00
25%,255114.00,18114.00,5305.00,17675.00,849.00,2004.00,60937.00,905.00,0.00,32124.00,3944.00,5027.00,5988.00,7242.00,3938.00,5054.00,6260.00,7478.00
30%,306137.00,18149.00,5600.00,18111.00,1056.00,2004.00,63991.00,975.00,0.00,32824.00,4338.00,5487.00,6430.00,7682.00,4339.00,5496.00,6684.00,7974.00
35%,357160.00,18170.00,5865.00,18880.00,1194.00,2004.00,66859.00,1053.00,0.00,33619.00,4737.00,5920.00,6916.00,8204.00,4736.00,5915.00,7200.00,8509.00
40%,408182.50,18204.00,6125.00,18881.00,1261.00,2005.00,69509.00,1113.00,0.00,37122.00,5160.00,6353.00,7415.00,8731.00,5144.00,6345.00,7678.00,9020.00
45%,459206.50,18245.00,6400.00,19064.00,1341.00,2005.00,71707.00,1113.00,0.00,37771.00,5543.00,6748.00,7906.00,9220.00,5545.00,6747.00,8147.00,9488.00
50%,510227.00,18290.00,6700.00,19638.00,1404.00,2005.00,73719.00,1113.00,0.00,64161.00,5985.00,7195.00,8336.00,9643.00,5949.00,7195.50,8616.00,9952.00
55%,561250.50,18325.00,7000.00,20207.00,1502.00,2006.00,75685.00,1113.00,0.00,74135.00,6388.00,7588.00,8788.00,10109.00,6367.00,7603.00,9099.00,10451.00
60%,612273.00,18365.00,7245.00,20740.00,1597.00,2006.00,77573.00,1155.00,0.00,75236.00,6806.00,7960.00,9278.00,10595.00,6757.00,7964.00,9576.00,10976.00
65%,663294.00,18400.00,7500.00,20928.00,1796.00,2006.00,79436.00,1243.00,0.00,76063.00,7150.00,8329.00,9726.00,11134.00,7135.00,8342.00,10062.00,11414.00
70%,714317.00,18435.00,7735.00,21053.00,1931.00,2006.00,81375.00,1353.00,0.00,78219.00,7513.00,8709.00,10245.00,11639.00,7508.00,8692.00,10564.00,11739.00
75%,765339.50,18471.00,8000.00,22808.00,2038.00,2007.00,83436.00,1497.00,0.00,80011.00,7892.00,9094.00,10755.00,12182.00,7878.00,9113.00,11079.00,12248.00
80%,816362.50,18513.00,8300.00,23359.00,2178.00,2007.00,84725.00,1623.00,0.00,80817.00,8266.00,9632.00,11342.00,12765.00,8262.00,9611.00,11405.00,12773.00
85%,867388.50,18547.00,8515.00,25100.00,2326.00,2008.00,86898.00,1763.00,0.00,85040.00,8867.00,10380.00,12037.00,13591.00,8872.00,10106.00,11957.00,13473.00
90%,918410.00,18563.00,9100.00,99740.00,2443.00,2008.00,89293.00,1974.00,0.00,89165.00,9833.00,11422.00,13191.00,14801.00,9834.00,11018.00,12836.00,14469.00
95%,969434.00,18589.00,9650.00,99761.00,2561.00,2009.00,93369.00,2198.00,0.00,92807.00,11792.00,13394.00,14292.00,16095.00,10750.00,12607.00,14419.00,16244.00
max,1020455.00,18626.00,45469.00,99761.00,2797.00,2010.00,115717.00,7498.00,1.00,99224.00,35722.00,36859.00,39080.00,41482.00,35722.00,36859.00,39080.00,41062.00

In [39]:
conn.droptable(name='CARDATA', caslib='casuser')

NOTE: Cloud Analytic Services dropped table CARDATA from caslib CASUSER(sasdemo).

+ Elapsed: 0.0614s, user: 0.035s, sys: 0.026s, mem: 0.0319mb

In [40]:
conn.close()

#### To learn more about the python SWAT API - check out the following resources

![alt text](https://www.sas.com/storefront/aux/en/splcpython/69194_thumbnailcover.jpg)

* Install the client library with a pip install
* Get the documenation of the swat package on https://sassoftware.github.io/python-swat/
* Developing applications with SAS Viya (Java,R,Python,Lua,REST) - [developer.sas.com](https://developer.sas.com)
* Follow **[SAS Software on github](https://github.com/sassoftware)**